### ISSUE TITLE
Add non-repro, simple CI checks all relevant config PRs

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/access-om2-configs#25]
References this comment: https://github.com/ACCESS-NRI/access-om2-configs/pull/23#issuecomment-1977968334

We don't need to go through the rigamarole of testing reproducibility for all PRs (only test that for `dev-*` into `release-*`) but we should still do some checks. See the referenced comment for the types of checks we want to do. These would run on all config-related PRs (`<some feature>` into `dev-*`, and `dev-*` into `release-*`).

**Comment by aidanheerdegen** [comment]
Some checks

- [ ] check `project` is **not** defined
- [ ] check `shortpath` is **not** defined
- [ ] absolute input paths
- [ ] all input paths in `vk83` (allow exceptions for jra55 data in IAF configs)
- [ ] all input paths point to files (allow exceptions for IAF forcing data)
- [ ] exe paths absolute. test for consistency of spack hash?
- [ ] mppnccombine-fast collate exe for high res configs
- [ ] test no storage flags in qsub flags
- [ ] check no scripts in top level directory (should be in `tools`)
- [ ] test `runlog` is on
- [ ] `restart_freq` is date based. Maybe define some acceptable values?
- [ ] sync **not** enabled, sync path **not** set

Many of these are available in an existing CI checking "library"

https://github.com/COSIMA/cleanconfig/blob/master/test.py

**Comment by aidanheerdegen** [comment]
Could use pytest markers to mark tests to assist in running only when required. e.g. `highres` marker could be used to switch on/off the `mppnccombine-fast` check

https://pytest-with-eric.com/pytest-best-practices/pytest-markers/

**Comment by aidanheerdegen** [comment]
@dougiesquire do you have any comments about the checks suggested above? Particularly the `metadata.yaml` fields? Should `access-om2-bgc` have an `ocean` *and* `ocnBgchem` realm?


And off topic, but hooo boy, there should be a special place in controlled vocabulary hell for the committee that thought `ocnBgchem` was better than `oceanbgc` or `oceanbiogeochem` or pretty much anything. Eeeuuwww.

**Comment by dougiesquire** [comment]
> Should access-om2-bgc have an `ocean` and `ocnBgchem` realm?

Seems sensible to me. FYI, this choice doesn't impact the catalog, which gets the realm per file. Currently there's no easy way to determine whether an ACCESS-OM2 MOM output file is `ocean` or `ocnBgchem` so everything is classified as `ocean`.

**Comment by aidanheerdegen** [comment]
Thanks.

I should have been more specific (as usual), I wasn't sure if `ocnBgchem` (feels awful just typing it) *implied* `ocean`. 

If we assume not, that both are required, we'll have the situation that the experiment specifies both realms, but none of the "file assets" (data files) have the `ocnBgchem` realm. I think that's fine, but we'll probably be first up against the wall if we stumble into an angry mob of ontologists (is there any other kind?).

**Comment by dougiesquire** [comment]
> I wasn't sure if `ocnBgchem` (feels awful just typing it) implied `ocean`

I see - I don't think we should _only_ include `ocnBgchem`. I think what's in the `realm` property of the `metadata.yaml` file should be the union of the realms for all the files in the experiment. `access-om2-bgc` has `seaIce` (CICE output) and `ocean` (most of MOM output) and `ocnBgchem` (MOM WOMBAT output).

> we'll have the situation that the experiment specifies both realms, but none of the "file assets" (data files) have the ocnBgchem realm.

I can't see this being a huge problem anytime soon. The only issue I can think of off the top of my head is if you are doing/planning something like writing code snippets to load data from the catalog based on the `metadata.yaml` file. Then its probably safest to just have `realm = ['ocean', 'seaIce']`.

**Comment by CodeGat** [comment]
> Could use pytest markers to mark tests to assist in running only when required. e.g. `highres` marker could be used to switch on/off the `mppnccombine-fast` check
> 
> https://pytest-with-eric.com/pytest-best-practices/pytest-markers/

@aidanheerdegen if we want to run different checks on different branches, we could add another `.json` file to the `config` folder on `main` that informs the CI (I seem to love those) regarding what markers to use. For example:

```json
{
  "markers": {
    "branches": {
      "release-1deg_jra55_ryf": "highres and config and metadata",
      "release-some_other_config": "config and metadata"
    }
  }
}
```

What do you think? (thanks for bringing it to my attention @jo-basevi

**Comment by aidanheerdegen** [comment]
> if we want to run different checks on different branches, we could add another `.json` file to the `config` folder on `main` that informs the CI (I seem to love those) regarding what markers to use

We *could* .. but equally we could also just interrogate the branch name

https://github.com/ACCESS-NRI/access-om2-configs/pull/32#issuecomment-2019849410

If the latter makes the CI too access-om2 specific, if otherwise it could be used more generically, then I'd be ok with a config file.

**Comment by CodeGat** [comment]
We could interrogate the branch, and do it all in a step, but that assumes that we will only ever have not many different styles of markers (`config or metadata` or `config or metadata or highes`) for branches. I've done up the config file in this PR, anyway - what do you think?

**Comment by aidanheerdegen** [comment]
I forgot a check! We also want this set in `config.yaml`
```yaml
manifest:
   reproduce:
      exe: True
```

**Comment by aidanheerdegen** [comment]
Another thought popped into my head because I had already made this mistake

https://github.com/ACCESS-NRI/access-om2-configs/blob/release-1deg_jra55_ryf/accessom2.nml#L19

It is common practice to reduce the `restart_period` (model run time) when testing a configuration, so we should check it is a "reasonable" value. 

Now .. what is reasonable? 

The one degree has a 5 year run time for both physics only and BGC:

https://github.com/COSIMA/1deg_jra55_ryf/blob/master/accessom2.nml#L19
https://github.com/COSIMA/1deg_jra55_ryf/blob/master%2Bbgc/accessom2.nml#L19

The quarter degree typically runs for 2 years at a time

https://github.com/COSIMA/025deg_jra55_ryf/blob/master/accessom2.nml#L20

but the BGC version is 1 year

https://github.com/COSIMA/025deg_jra55_ryf/blob/master%2Bbgc/accessom2.nml#L20

The tenth degree only runs 3 months at a time

https://github.com/COSIMA/01deg_jra55_ryf/blob/master/accessom2.nml#L22

and the BGC version is 1 month

https://github.com/COSIMA/01deg_jra55_ryf/blob/master%2Bbgc/accessom2.nml#L22

**Comment by aidanheerdegen** [comment]
It would be good to control (limit) the acceptable keywords in the configurations, partly to provide guidance on what should be used because everyone will come up with their own.

Keywords are a bit of a wild-west and it doesn't seem there are many definitive vocabularies of keywords available, but the [Global Change Master Directory (GCMD) Keywords](https://www.earthdata.nasa.gov/learn/find-data/idn/gcmd-keywords) might be one. It might be overkill but it is a great resource, e.g.

https://gcmd.earthdata.nasa.gov/KeywordViewer/scheme/all/10a128a6-12d4-4bce-b25d-2ffc464182f4?gtm_keyword=POLYNYAS&gtm_scheme=Earth%20Science

So .. a list of acceptable keywords (please others add your opinions):

| Topic | Keywords (mutually exclusive) |
|--|--|
| Spatial extent | global, regional |
| Forcing product | JRA55, ERA5 |
| Forcing mode | repeat-year, ryf, repeat-decade, rdf, interannual, iaf |
| Model | access-om2 | access-om2-025 | access-om2-01 |

I've intentionally left off organisational keywords because that [should be covered in the metadata right](https://github.com/ACCESS-NRI/schema/issues/17)? Also it might not be mutually exclusive. We should definitely credit COSIMA because they developed these configurations, but also ACCESS-NRI is supporting them now.

**Comment by aidanheerdegen** [comment]
Speaking of controlled vocabularies, we need to populate the `nominal resolution` field in the `metadata.yaml` with something useful.

From [this CMIP6 example](https://wcrp-cmip.org/cmip-model-and-experiment-documentation/) it seems like a distance measure is the normal approach and the respective values should be

| Config resolution | Nominal Resolution |
| -- | -- |
| 1deg | 100 km |
| 025deg | 25 km |
| 01deg | 10 km |

Does that look right to you @aekiss ?

**Comment by dougiesquire** [comment]
Note the CMIP6 controlled vocab [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_nominal_resolution.json). Most are distance measures as you said.

**Comment by aekiss** [comment]
I think that's close enough and would be familiar to people. Of course it depends on latitude etc. eg see table 6 and fig 5 of the tech report
<img width="883" alt="Screenshot 2024-03-28 at 2 48 59 pm" src="https://github.com/ACCESS-NRI/access-om2-configs/assets/31054815/feb536ca-b132-4dcc-b549-31b9c7ea16c0">
<img width="874" alt="Screenshot 2024-03-28 at 2 50 05 pm" src="https://github.com/ACCESS-NRI/access-om2-configs/assets/31054815/1df0471e-c94e-4885-89c6-df3a0c270c12">

**Comment by aidanheerdegen** [comment]
> Note the CMIP6 controlled vocab is [here](https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_nominal_resolution.json). Most are distance measures as you said.

Thanks. WCRP "Controlled" vocabulary I have a `1x1 degree` bone to pick with you.

https://github.com/WCRP-CMIP/CMIP6_CVs/blob/main/CMIP6_nominal_resolution.json#L9

**Comment by aidanheerdegen** [comment]
> I think that's close enough and would be familiar to people. Of course it depends on latitude etc. eg see table 6 and fig 5 of the tech report

Absolute distance is a terrible measure eh? "ballpark resolution" might be a better name. 

Should we use `1x1 degree`, `0.25x0.25 degree` and `0.1x0.1 degree`?

We don't *have* to follow CMIP6.

**Comment by aekiss** [comment]
Absolute distance is worse than degrees, but degrees are also not great (meridional resolution in degrees is also latitude-dependent due to Mercator grid, and then there's the tripolar region). I guess that's why they hedge it with "nominal".

**Comment by aidanheerdegen** [comment]
And at least distance has some vague meaning for normal people I guess.
